Repository FESI-7-4/mirujima_FE, pull requests merged in 2025-02, with the labels that each got.

#44 feat: 할 일 별 노트 모아보기 페이지
  api/clientActions/authApi.ts
  api/clientActions/index.ts
  api/clientActions/note.ts
  api/clientActions/readTodoList.ts
  api/clientActions/route.ts
  api/index.ts
  api/note.ts
  api/serverActions/index.ts
  api/serverActions/note.ts
  app/(note)/_components/noteCard/NoteCard.tsx
  app/(note)/_components/noteCardList/NoteCardList.tsx
  app/(note)/_components/noteContent/NoteContent.tsx
  app/(note)/noteList/(.)notes/[id]/page.tsx
  app/(note)/noteList/page.tsx
  app/(note)/notes/create/page.tsx
  app/todoList/page.tsx
  hooks/auth/useLoginMutation.ts
  hooks/auth/useSignUpMutation.ts
  next.config.ts
  public/icon/more.svg
  tailwind.config.ts
  types/apiResponse.type.ts
  types/goal.type.ts
  types/note.type.ts
  types/todo.type.ts
Labels: 🍅sprint_2

#59 style: 비밀번호 눈 아이콘 추가
  app/(auth)/_components/Header.tsx
  app/(auth)/_components/InputField.tsx
  app/(auth)/login/page.tsx
  public/icon/eye-closed-black.svg
  public/icon/eye-closed-gray.svg
  public/icon/eye-opened-black.svg
  public/icon/eye-opened-gray.svg
  public/images/logo/mirujima-logo-with-tmt.svg
Labels: 🍅sprint_2

#61 style: 노트 작성, 리스트 페이지 디자인 반영
  api/clientActions/note.ts
  api/serverActions/note.ts
  app/(note)/_components/noteCard/NoteCard.tsx
  app/(note)/_components/noteContent/NoteContent.tsx
  app/(note)/_components/noteContent/editor/Editor.tsx
  app/(note)/_components/noteContent/editor/editor.css
  app/(note)/_components/noteContent/titleInput/TitleInput.tsx
  app/(note)/noteList/page.tsx
  app/(note)/notes/create/page.tsx
  public/icon/work.svg
  tailwind.config.ts
  types/todo.type.ts
Labels: 🍅sprint_2

#64 feat: 목표 상세 페이지 todo 없을때
  app/goals/[id]/page.tsx
  app/goals/_components/Button.tsx
  app/goals/_components/TaskList.tsx
Labels: 🍅sprint_2

#67 chore: 세팅 문서값 수정
  build.sh
Labels: 🍅sprint_2

#65 feat: 할 일 생성 모달 css 및 수정 추가
  app/AllProviders.tsx
  app/goals/[id]/pages.tsx
  app/todoList/(.)notes/[id]/layoutes.tsx
  components/navBar/Menus.tsx
  components/navBar/index.tsx
  constant/numbers.ts
  hooks/useIsSmallScreen.ts
  modals/CloseButton.tsx
  modals/Overlay.tsx
  modals/todoCreateCheckModal/index.tsx
  modals/todoCreateModal/DoneChecker.tsx
  modals/todoCreateModal/GoalSelector.tsx
  modals/todoCreateModal/PrioritySelector.tsx
  modals/todoCreateModal/SubmitButton.tsx
  modals/todoCreateModal/TitleInput.tsx
  modals/todoCreateModal/Uploader.tsx
  modals/todoCreateModal/index.tsx
  modals/todoCreateModal/type.ts
  modals/todoCreateModal/useSetTodoEditValue.ts
  modals/todoCreateModal/useTodoCreatValidCheck.ts
  provider/store-provider.tsx
  public/icon/X.svg
  public/icon/add-gray.svg
  stores/modalStore.ts
  stores/todoModalStore.ts
Labels: 🍅sprint_2

#68 feat: 노트 모아보기 무한스크롤 적용
  api/clientActions/note.ts
  api/serverActions/goal.ts
  api/serverActions/index.ts
  api/serverActions/interceptors/request.ts
  api/serverActions/interceptors/response.ts
  api/serverActions/note.ts
  app/(note)/_components/noteCardList/NoteCardList.tsx
  app/(note)/_components/noteContent/NoteContent.tsx
  app/(note)/noteList/[goalId]/not-found.tsx
  app/(note)/noteList/[goalId]/page.tsx
  app/(note)/noteList/page.tsx
  app/goals/[id]/page.tsx
  components/icons/CloseIcon.tsx
  hooks/note/useInfiniteNoteList.ts
  hooks/useReactQuery.tsx
  package.json
  types/apiResponse.type.ts
  types/goal.type.ts
  types/note.type.ts
Labels: 🍅sprint_2

#74 Feat: 목표 상세 페이지 및 리퀘스트 인터셉터
  api/interceptors/requestInterceptors.ts
  api/interceptors/responseInterceptors.ts
  app/goals/[id]/page.tsx
  app/goals/[id]/pages.tsx
  app/goals/_components/TaskList.tsx
  app/goals/_components/TodoItem.tsx
  hooks/goalsDetail/useCheckTodoStatus.ts
  hooks/goalsDetail/useGetGoalDetail.ts
  hooks/goalsDetail/useGetTodoList.ts
  next.config.ts
Labels: 🍅sprint_2

#76 feat: 노트 수정 기능
  api/clientActions/note.ts
  api/serverActions/index.ts
  api/serverActions/note.ts
  api/serverActions/todo.ts
  app/(note)/_components/modals/uploadLinkModal/UploadLinkModal.tsx
  app/(note)/_components/noteCardList/NoteCardList.tsx
  app/(note)/_components/noteContent/NoteContent.tsx
  app/(note)/_components/noteContent/editor/Editor.tsx
  app/(note)/_components/noteContent/editor/editor.css
  app/(note)/_components/noteContent/editor/linkToolbarButton/LinkToolbarButton.tsx
  app/(note)/_components/noteContent/titleInput/TitleInput.tsx
  app/(note)/noteList/[goalId]/page.tsx
  app/(note)/notes/create/page.tsx
  constant/regex.ts
  hooks/goalsDetail/useGetGoalDetail.ts
  hooks/goalsDetail/useGetTodoList.ts
  schema/noteSchema.ts
  types/apiResponse.type.ts
  types/note.type.ts
  types/todo.type.ts
  utils/note/convertDataForEditor.ts
Labels: 🍅sprint_2

#79 feat: 노트 삭제 기능
  api/clientActions/note.ts
  api/serverActions/interceptors/response.ts
  app/(note)/_components/noteCard/NoteCard.tsx
  app/(note)/_components/noteCardList/NoteCardList.tsx
  app/(note)/_components/noteContent/NoteContent.tsx
  app/goals/_components/TodoItem.tsx
  app/todoList/_components/TodoItem.tsx
  components/kebab/KebabMenu.tsx
  hooks/goalsDetail/useInfiniteTodoList.ts
  hooks/note/useDeleteNote.ts
  hooks/note/useInfiniteNoteList.ts
  types/note.type.ts
Labels: 🍅sprint_2

#96 style: 로그인, 회원가입 반응형
  app/(auth)/_components/Button.tsx
  app/(auth)/_components/InputField.tsx
  app/(auth)/layout.tsx
  app/(auth)/login/page.tsx
  app/(auth)/signup/page.tsx
  app/(workspace)/goals/_components/Button.tsx
Labels: 🧀sprint_3

#98 style: 목표 상세 페이지
  apis/todo.ts
  app/(workspace)/goals/[id]/page.tsx
  app/(workspace)/goals/_components/TaskList.tsx
  app/(workspace)/goals/_components/TodoItem.tsx
  components/kebab/KebabForGoal.tsx
  components/navBar/SmallNav.tsx
  hooks/goalsDetail/useCheckTodoStatus.ts
  public/icon/note-s.svg
Labels: 🧀sprint_3

#101 feat: 할 일 생성 모달 api 추가
  app/(auth)/login/page.tsx
  app/(workspace)/todoList/_components/TodoItem.tsx
  app/(workspace)/todoList/page.tsx
  app/AllProviders.tsx
  app/ModalArea.tsx
  app/dashboard/_components/LatestTodoList.tsx
  components/navBar/Menus/NewGoalButton.tsx
  components/navBar/Menus/index.tsx
  components/navBar/index.tsx
  hooks/goalsDetail/useDeleteGoal.ts
  hooks/nav/useInfinityGoalList.ts
  hooks/nav/useIsSmallScreen.ts
  hooks/nav/useNewGoalInput.ts
  hooks/nav/useResize.ts
  hooks/nav/useSetNewGoal.ts
  hooks/todoCreate/useS3Upload.ts
  hooks/todoCreate/useSetTodoCreate.ts
  hooks/todoCreate/useTodoCreatValidCheck.ts
  hooks/todoCreate/useTodoEdit.ts
  hooks/useGetGoalList.ts
  modals/todoCreateCheckModal/index.tsx
  modals/todoCreateModal/DoneChecker.tsx
  modals/todoCreateModal/GoalSelector.tsx
  modals/todoCreateModal/PrioritySelector.tsx
  modals/todoCreateModal/SubmitButton.tsx
  modals/todoCreateModal/TitleInput.tsx
  modals/todoCreateModal/Uploader.tsx
  modals/todoCreateModal/index.tsx
  modals/todoCreateModal/type.ts
  modals/todoCreateModal/useSetTodoEditValue.ts
  modals/todoCreateModal/useTodoCreatValidCheck.ts
  provider/store-provider.tsx
  stores/modalStore.ts
  stores/todoCreateModalStore.ts
  stores/todoModalStore.ts
  utils/dateUtils.ts
Labels: 🧀sprint_3

#103 feat: 목표 수정, 삭제 모달
  app/(workspace)/goals/[id]/page.tsx
  app/(workspace)/goals/_components/GoalDeleteConfirmModal.tsx
  app/(workspace)/goals/_components/GoalEditModal.tsx
  app/ModalArea.tsx
  components/modal/GoalDeleteConfirmModal.tsx
  modals/Overlay.tsx
  stores/modalStore.ts
  tailwind.config.ts
Labels: 🧀sprint_3

#111 fix: 노트 모아보기에서 노트 수정 클릭 시 route 오류 수정
  app/(workspace)/(note)/_components/noteCardList/NoteCardList.tsx
  app/(workspace)/(note)/_components/noteCardList/noteCard/NoteCard.tsx
  app/(workspace)/(note)/notes/create/[todoId]/page.tsx
  components/kebab/KebabMenu.tsx
Labels: 🧀sprint_3

#114 feat: nav바 수정사항 반영
  apis/clientActions/index.ts
  apis/clientActions/s3.ts
  app/(workspace)/(note)/noteList/@note/(...)notes/[id]/layout.tsx
  app/(workspace)/(note)/noteList/[goalId]/layout.tsx
  app/(workspace)/(note)/notes/[id]/layout.tsx
  app/(workspace)/(note)/notes/create/layout.tsx
  app/(workspace)/goals/[id]/layout.tsx
  app/(workspace)/todoList/layout.tsx
  app/ModalArea.tsx
  app/dashboard/layout.tsx
  components/loading/DotLoading.tsx
  components/loading/SpinLoading.tsx
  components/loading/TomatoFill.tsx
  components/loading/TomatoGradation.tsx
  components/navBar/Info/ProfileImage.tsx
  components/navBar/Info/index.tsx
  components/navBar/LargeNav.tsx
  components/navBar/MediumNav.tsx
  components/navBar/Menus/GoalList.tsx
  components/navBar/Menus/NewGoalButton.tsx
  components/navBar/Menus/index.tsx
  components/navBar/SmallNav.tsx
  components/navBar/index.tsx
  hooks/nav/useInfinityGoalList.ts
  hooks/nav/useProfileImageEdit.ts
  hooks/nav/useScrollUpdate.ts
  hooks/nav/useSetNewGoal.ts
  hooks/todoCreate/useS3Upload.ts
  hooks/useGetGoalList.ts
  middleware.ts
  modals/goalCreateModal/index.tsx
  modals/loadingOverlay/Loading.tsx
  modals/todoCreateModal/GoalSelector.tsx
  modals/todoCreateModal/SubmitButton.tsx
  next.config.ts
  public/icon/nav-note-list.svg
  public/icon/nav-todo-list.svg
  public/icon/photo-add.svg
  public/icon/spin.svg
  public/images/logo/mirujima-logo-tomato.png
  public/images/logo/stem.png
  public/images/temp.png
  stores/infoStore.ts
  stores/modalStore.ts
  tailwind.config.ts
Labels: 🧀sprint_3

#126 feat: 할 일 체크하면 달성률 반영
  app/(workspace)/goals/[id]/page.tsx
  components/TaskList/TaskList.tsx
  components/TodoItem/TodoItem.tsx
  hooks/goalsDetail/useCheckTodoStatus.ts
  hooks/goalsDetail/useGetGoalDetail.ts
  hooks/goalsDetail/useGetTodoList.ts
  types/todo.type.ts
  utils/dashboard/getWeeklyCompletionCounts.ts
Labels: 🍔sprint_4

#128 style: 목표 상세 페이지 태블릿, 모바일 디자인 변경
  app/(workspace)/goals/[id]/page.tsx
  app/dashboard/_components/GoalList.tsx
  components/TaskList/TaskList.tsx
Labels: 🍔sprint_4

#124 feat: 노트 링크 콘텐츠 임베드
  app/(workspace)/(note)/_components/embedContent/EmbedContent.tsx
  app/(workspace)/(note)/_components/noteContent/NoteContent.tsx
  app/(workspace)/(note)/_components/noteContent/editor/Editor.tsx
  app/(workspace)/(note)/_components/noteContent/editor/linkToolbarButton/LinkToolbarButton.tsx
  app/(workspace)/(note)/_components/noteContent/goalAndTodoInfo/GoalAndTodoInfo.tsx
  app/(workspace)/(note)/_components/noteContent/linkArea/LinkArea.tsx
  app/(workspace)/(note)/_components/readOnlyNoteContent/ReadOnlyNoteContent.tsx
  app/(workspace)/(note)/_components/readOnlyNoteContent/readOnlyEditor/DynamicReadOnyEditor.tsx
  app/(workspace)/(note)/noteList/@note/(...)notes/[id]/modal.tsx
  app/(workspace)/(note)/noteList/@note/(...)notes/[id]/page.tsx
  app/(workspace)/(note)/noteList/[goalId]/page.tsx
  app/(workspace)/(note)/notes/[id]/page.tsx
  app/(workspace)/(note)/notes/create/[todoId]/page.tsx
  hooks/note/useEditor.ts
  stores/modalStore.ts
  types/note.type.ts
Labels: 🧀sprint_3, 🍔sprint_4

#135 style: 노트 관련 페이지 css 수정
  app/(workspace)/(note)/_components/embedContent/EmbedContent.tsx
  app/(workspace)/(note)/_components/goalNoteList/GoalNoteList.tsx
  app/(workspace)/(note)/_components/goalNoteList/goalNoteListContent/GoalNoteListContent.tsx
  app/(workspace)/(note)/_components/modals/lodaTempNoteConfirmModal/LoadTempNoteConfirmModal.tsx
  app/(workspace)/(note)/_components/modals/uploadLinkModal/UploadLinkModal.tsx
  app/(workspace)/(note)/_components/noteCardList/noteCard/NoteCard.tsx
  app/(workspace)/(note)/_components/noteContent/NoteContent.tsx
  app/(workspace)/(note)/_components/noteContent/buttonArea/ButtonArea.tsx
  app/(workspace)/(note)/_components/noteContent/editor/Editor.tsx
  app/(workspace)/(note)/_components/noteContent/editor/editor.css
  app/(workspace)/(note)/_components/noteContent/goalAndTodoInfo/GoalAndTodoInfo.tsx
  app/(workspace)/(note)/_components/noteContent/titleInput/TitleInput.tsx
  app/(workspace)/(note)/_components/readOnlyNoteContent/ReadOnlyNoteContent.tsx
  app/(workspace)/(note)/_components/todoChip/TodoChip.tsx
  app/(workspace)/(note)/noteList/@note/(...)notes/[id]/modal.tsx
  app/(workspace)/(note)/noteList/[goalId]/page.tsx
  app/(workspace)/layout.tsx
  app/AllProviders.tsx
  app/globals.css
  public/icon/arrow-up.svg
  tailwind.config.ts
Labels: 🍔sprint_4

#136 bug: 검수 내용 해결 및 수정
  app/(workspace)/(note)/_components/editGoal/EditGoal.tsx
  app/(workspace)/goals/[id]/page.tsx
  app/(workspace)/goals/_components/GoalEditModal.tsx
  app/(workspace)/todoList/_components/EmptyMessage.tsx
  app/dashboard/_components/GoalItem.tsx
  app/dashboard/_components/GoalList.tsx
  components/TaskList/TaskList.tsx
  components/TodoItem/TodoItem.tsx
  components/kebab/KebabForGoal.tsx
  hooks/goalsDetail/useDeleteGoal.ts
Labels: 🍔sprint_4

#151 fix: 노트 리스트페이지 목표 수정 바로 반영
  app/(workspace)/(note)/_components/editGoal/EditGoal.tsx
Labels: 🍔sprint_4

#155 feat: 노트의 링크가 유튜브일 때 임베드 링크로 변환하는 기능
  app/(workspace)/(note)/_components/embedContent/EmbedContent.tsx
  utils/note/convertYoutubeLinkToEmbedUrl.ts
Labels: 🍔sprint_4

#159 feat: 목표 없는 할 일의 노트 추가/수정
  app/(workspace)/(note)/_components/noteContent/NoteContent.tsx
  app/(workspace)/(note)/_components/noteContent/noteInfo/NoteInfo.tsx
  app/(workspace)/(note)/_components/readOnlyNoteContent/ReadOnlyNoteContent.tsx
  constant/toastText.ts
  hooks/note/useNoteActions.ts
  hooks/note/useTempNote.ts
  types/note.type.ts
Labels: 🍔sprint_4
