Repository FESI-7-4/mirujima_FE, pull requests merged in 2025-03, with the labels that each got.

#169 fix: 구글 린트, 프리티어 적용
  .coderabbit.yml
  .eslintrc
  .github/ISSUE_TEMPLATE/bug-report-template.md
  .github/ISSUE_TEMPLATE/feature-template.md
  .github/PULL_REQUEST_TEMPLATE.md
  .prettierrc
  README.md
  apis/clientActions/s3.ts
  apis/interceptors/requestInterceptors.ts
  apis/serverActions/goal.ts
  apis/serverActions/interceptors/response.ts
  app/(workspace)/(note)/_components/editGoal/EditGoal.tsx
  app/(workspace)/(note)/_components/noteContent/NoteContent.tsx
  app/(workspace)/(note)/noteList/@note/(...)notes/[id]/layout.tsx
  app/(workspace)/(note)/noteList/[goalId]/layout.tsx
  app/(workspace)/(note)/notes/[id]/layout.tsx
  app/(workspace)/(note)/notes/create/layout.tsx
  app/(workspace)/goals/[id]/layout.tsx
  app/(workspace)/goals/[id]/page.tsx
  app/(workspace)/todoList/layout.tsx
  app/dashboard/_components/calendar/index.tsx
  app/page.tsx
  components/TaskList/TaskList.tsx
  components/TodoItem/TodoItem.tsx
  components/navBar/Info/ProfileImage.tsx
  hooks/auth/useLoginMutation.ts
  hooks/goalsDetail/useDeleteGoal.ts
  hooks/note/useInfiniteNoteList.ts
  hooks/note/useTempNote.ts
  hooks/todoCreate/useSetTodoCreate.ts
  jest.config.ts
  modals/todoCreateModal/DoneChecker.tsx
  modals/todoCreateModal/GoalSelector.tsx
  modals/todoCreateModal/SubmitButton.tsx
  modals/todoCreateModal/Uploader.tsx
  package.json
  postcss.config.mjs
  provider/store-provider.tsx
  types/types.ts
  utils/dateUtils.ts
Labels: 🦩 sprint_5

#177 refactor: 대시보드 하이드레이션 에러 처리 및 UX 개선
  app/(workspace)/todoList/page.tsx
  app/dashboard/_components/LatestTodoList.tsx
  app/dashboard/_components/UpcomingGoals.tsx
  app/dashboard/_components/goals/GoalItem.tsx
  app/dashboard/_components/goals/TaskSection.tsx
  app/dashboard/_components/weeklyChart/index.tsx
  components/TaskList/TaskList.tsx
  components/TodoItem/TodoItem.tsx
  components/kebab/KebabForGoal.tsx
  hooks/goal/useInfiniteGoalList.ts
  hooks/goalsDetail/useGetTodoList.ts
  types/todo.type.ts
Labels: 🦩 sprint_5

#181 feature/뽀모도로 타이머
  app/layout.tsx
  components/Confetti/index.tsx
  components/PomodoroTimer/index.tsx
  package.json
  tailwind.config.ts
Labels: 🦩 sprint_5

#179 fix: 달성률에 따라 달력 날짜에 배경 색상 미적용 문제 해결
  utils/dashboard/getBgColorForGoal.ts
Labels: 🐞bug

#183 refactor: 우선순위 색상 적용 에러 해결 및 colors 관련 타입 개선
  app/dashboard/_components/calendar/Label.tsx
  app/dashboard/_components/calendar/index.tsx
  components/TodoItem/TodoItem.tsx
  constant/colors.ts
  constant/priorityColor.ts
  tailwind.config.ts
  types/color.type.ts
Labels: 🐞bug, 🦩 sprint_5, ♻refactor

#176 refactor: 타입스크립트 정리
  apis/serverActions/todo.ts
  app/(auth)/login/page.tsx
  app/(auth)/signup/page.tsx
  app/(workspace)/(note)/_components/editGoal/EditGoal.tsx
  app/(workspace)/(note)/_components/goalNoteList/GoalNoteList.tsx
  app/(workspace)/(note)/noteList/page.tsx
  app/(workspace)/goals/[id]/page.tsx
  app/(workspace)/goals/_components/NoteDetailModal.tsx
  app/(workspace)/todoList/_components/EmptyMessage.tsx
  app/dashboard/_components/UpcomingGoals.tsx
  app/dashboard/_components/goals/GoalProgressBar.tsx
  app/globals.css
  components/TodoItem/TodoItem.tsx
  components/navBar/Menus/GoalList.tsx
  hooks/goalsDetail/useChangeGoalTitle.ts
  hooks/goalsDetail/useCheckTodoStatus.ts
  hooks/goalsDetail/useGetGoalDetail.ts
  hooks/goalsDetail/useGetTodoList.ts
  hooks/useGetGoalList.ts
  modals/todoCreateModal/GoalSelector.tsx
  modals/todoCreateModal/SubmitButton.tsx
  modals/todoCreateModal/Uploader.tsx
  modals/todoCreateModal/index.tsx
  modals/todoCreateModal/type.ts
  provider/store-provider.tsx
  stores/embedStore.ts
  stores/infoStore.ts
  stores/modalStore.ts
  stores/todoCreateModalStore.ts
  types/ISODateString.type.ts
  types/embedStore.types.ts
  types/goal.type.ts
  types/infoStore.types.ts
  types/modalStore.types.ts
  types/note.type.ts
  types/todo.type.ts
  types/todoCreateModal.types.ts
  types/types.ts
  utils/dashboard/getBgColorForGoal.ts
  utils/dashboard/getCompletedGoalCounts.ts
  utils/dashboard/getWeeklyCompletionCounts.ts
  utils/dashboard/goalUtil.ts
Labels: 🦩 sprint_5

#184 refactor: 노트 관련 코드 정리
  app/(workspace)/(note)/_components/editGoal/EditGoal.tsx
  app/(workspace)/(note)/_components/noGoalNoteList/NoGoalNoteList.tsx
  app/(workspace)/(note)/_components/noteCardList/NoteCardList.tsx
  app/(workspace)/(note)/_components/noteContent/NoteContent.tsx
  app/(workspace)/(note)/_components/noteContent/editor/editor.css
  app/(workspace)/(note)/_components/noteContent/noteInfo/NoteInfo.tsx
  app/(workspace)/(note)/noteList/[goalId]/page.tsx
  app/(workspace)/(note)/noteList/page.tsx
  app/dashboard/page.tsx
  constant/toastText.ts
  hooks/goal/useGoalActions.ts
  hooks/goalsDetail/useChangeGoalTitle.ts
  hooks/note/useDeleteNote.ts
  hooks/note/useInfiniteNoteList.ts
  hooks/note/useNoteActions.ts
  hooks/note/useTempNote.ts
  utils/dateUtils.ts
Labels: 🦩 sprint_5

#187 feat: pwa 적용
  .gitignore
  app/layout.tsx
  app/manifest.ts
  middleware.ts
  next.config.ts
  package.json
  public/images/android/android-chrome-192x192.png
  public/images/android/android-chrome-512x512.png
  public/images/favicon/favicon-16x16.png
  public/images/favicon/favicon-32x32.png
  public/images/favicon/favicon.ico
  public/images/ios/apple-touch-icon.png
Labels: 🦩 sprint_5

#188 feat/뽀모도로 타이머 개선 및 자잘한 로직, 애니메이션 수정 및 추가
  app/(auth)/_components/InputField.tsx
  app/(auth)/login/page.tsx
  app/dashboard/_components/goals/GoalProgressBar.tsx
  app/dashboard/_components/weeklyChart/Chart.tsx
  app/dashboard/_components/weeklyChart/index.tsx
  app/dashboard/layout.tsx
  app/layout.tsx
  components/PomodoroTimer/Layout.tsx
  components/PomodoroTimer/Timer.tsx
  components/PomodoroTimer/index.tsx
  components/confettis/Confetti.tsx
  components/confettis/PartyPopper.tsx
  components/navBar/MediumNav.tsx
  components/navBar/Menus/index.tsx
  components/navBar/index.tsx
  constant/numbers.ts
  hooks/auth/useLoginMutation.ts
  hooks/nav/useIsSmallScreen.ts
  hooks/nav/useResize.ts
  hooks/nav/useScrollUpdate.ts
  hooks/pomodoro/useConfetti.ts
  hooks/pomodoro/useIsDrag.ts
  hooks/pomodoro/usePosition.ts
  modals/Overlay.tsx
  package.json
  tailwind.config.ts
  types/pomodoro.type.ts
Labels: 🦩 sprint_5

#197 feat: 바벨 설정 추가
  .github/workflows/main.yml
  app/(workspace)/(note)/_components/noteCardList/NoteCardList.tsx
  app/(workspace)/(note)/noteList/page.tsx
  app/(workspace)/todoList/_components/TodoFilter.tsx
  app/(workspace)/todoList/page.tsx
  app/dashboard/_components/LatestTodoList.tsx
  app/dashboard/_components/UpcomingGoals.tsx
  app/dashboard/_components/calendar/index.tsx
  components/NavigationBar/Menus/GoalList.tsx
  components/TaskList/TaskList.tsx
  components/confettis/Confetti.tsx
  modals/todoCreateModal/GoalSelector.tsx
  next.config.ts
  package.json
Labels: 🏔️sprint6

#199 feat: any 타입 없애기
  apis/interceptors/requestInterceptors.ts
  apis/interceptors/responseInterceptors.ts
  apis/serverActions/interceptors/response.ts
  hooks/goalsDetail/useChangeGoalTitle.ts
  hooks/nav/useScrollUpdate.ts
  types/modalStore.types.ts
  utils/note/isTempNoteContent.ts
Labels: 🏔️sprint_6

#202 feat: 할 일의 파일 및 링크 아이콘 기능 추가
  apis/clientActions/todo.ts
  app/dashboard/_components/weeklyChart/index.tsx
  components/TodoItem/TodoItem.tsx
  hooks/todo/useTodoFileDownload.ts
Labels: 🏔️sprint_6

#200 feat: 프로젝트 mvp설문 피드백 기능 작업
  .github/workflows/main.yml
  components/PomodoroTimer/index.tsx
  components/PomodoroTimer/useIsClick.ts
  hooks/pomodoro/useIsDrag.ts
  hooks/pomodoro/usePosition.ts
  hooks/todoCreate/useDragAndDrop.ts
  hooks/useReactQuery.tsx
  modals/Overlay.tsx
  modals/goalCreateModal/index.tsx
  modals/todoCreateModal/GoalSelector.tsx
  modals/todoCreateModal/PrioritySelector.tsx
  modals/todoCreateModal/TitleInput.tsx
  modals/todoCreateModal/Uploader.tsx
  package.json
Labels: 🏔️sprint_6

#206 feat: sns로그인
  app/(auth)/_components/LoginForm.tsx
  app/(auth)/_components/SocialLoginButtons.tsx
  app/(auth)/auth/callback/page.tsx
  app/(auth)/login/page.tsx
  app/(workspace)/todoList/page.tsx
  app/AllProviders.tsx
  app/dashboard/_components/LatestTodoList.tsx
  components/NavigationBar/Menus/index.tsx
  components/NavigationBar/index.tsx
  components/TaskList/TaskList.tsx
  constant/cookieOptions.ts
  constant/toastText.ts
  hooks/auth/useAuthCheck.ts
  hooks/auth/useGoogleLoginMutation.ts
  hooks/auth/useKakaoLoginMutation.ts
  hooks/auth/useLoginMutation.ts
  middleware.ts
  next.config.ts
  stores/modalStore.ts
  types/auth.types.ts
  types/goal.type.ts
  utils/getGoogleLoginUrl.ts
  utils/getKakaoLoginUrl.ts
  utils/utils.ts
Labels: 🏔️sprint_6

#209 feat: 랜딩 페이지
  apis/clientActions/authApi.ts
  apis/clientActions/interceptors/requestInterceptors.ts
  apis/clientActions/interceptors/responseInterceptors.ts
  apis/clientActions/route.ts
  apis/serverActions/interceptors/response.ts
  app/(auth)/_components/Header.tsx
  app/ModalArea.tsx
  app/_components/PWAButton/PWAButton.tsx
  app/_components/heroImages/HeroImages.tsx
  app/_components/introText/IntroText.tsx
  app/page.tsx
  components/NavigationBar/index.tsx
  constant/toastText.ts
  hooks/pwa/useCheckInstalled.ts
  hooks/pwa/useDevice.ts
  hooks/pwa/usePWA.ts
  middleware.ts
  modals/iOSPWAGuideModal/IOSPWAGuideModal.tsx
  public/icon/add-ios.svg
  public/icon/dock.svg
  public/icon/share-ios.svg
  public/images/icons/flag-icon.svg
  public/images/landing/hero.png
  public/images/thumbnail/mirujima-thumbnail.svg
  stores/modalStore.ts
  tailwind.config.ts
  types/modalStore.types.ts
  types/note.type.ts
  utils/pwa.ts
Labels: 🏔️sprint_6

#213 feat: 할 일 삭제 확인 모달 추가
  apis/clientActions/todo.ts
  app/ModalArea.tsx
  components/TodoItem/TodoItem.tsx
  hooks/goalsDetail/useDeleteTodoItem.ts
  modals/todoDeleteConfirmModal/TodoDeleteConfirmModal.tsx
  stores/modalStore.ts
Labels: 🏔️sprint_6

#212 feat: 노트 상세 페이지 범위 수정
  apis/clientActions/note.ts
  app/(workspace)/(note)/noteList/@note/(...)notes/[id]/modal.tsx
  app/(workspace)/(note)/noteList/layout.tsx
  app/(workspace)/goals/_components/NoteDetailModal.tsx
  app/@note/(.)notes/[id]/layout.tsx
  app/@note/(.)notes/[id]/modal.tsx
  app/@note/(.)notes/[id]/page.tsx
  app/@note/[...catchAll]/page.tsx
  app/@note/default.tsx
  app/ModalArea.tsx
  app/layout.tsx
  components/TodoItem/TodoItem.tsx
  public/icon/arrow-right-black.svg
  stores/modalStore.ts
  types/modalStore.types.ts
Labels: 🏔️sprint_6

#216 feat: 노트 관련 버튼에 쓰로틀링 적용
  app/(workspace)/(note)/_components/noteContent/NoteContent.tsx
  hooks/note/useDeleteNote.ts
  hooks/note/useNoteActions.ts
  tailwind.config.ts
Labels: 🏔️sprint_6

#219 style: 랜딩, 노트 관련 페이지 버튼 호버 스타일 추가
  app/(workspace)/(note)/_components/embedContent/EmbedContent.tsx
  app/(workspace)/(note)/_components/modals/noteConfirmModal/NoteConfirmModal.tsx
  app/(workspace)/(note)/_components/modals/uploadLinkModal/UploadLinkModal.tsx
  app/(workspace)/(note)/_components/noteContent/buttonArea/ButtonArea.tsx
  app/(workspace)/(note)/_components/noteContent/editor/Editor.tsx
  app/(workspace)/(note)/_components/noteContent/tempNote/TempNote.tsx
  app/_components/PWAButton/PWAButton.tsx
  components/NavigationBar/Menus/GoalList.tsx
  components/NavigationBar/Menus/index.tsx
  hooks/note/useEditor.ts
  modals/iOSPWAGuideModal/IOSPWAGuideModal.tsx
  next.config.ts
  tailwind.config.ts
Labels: 🏔️sprint_6

#224 bug: 케밥 안 보이는 버그 css로 해결
  app/(workspace)/goals/[id]/page.tsx
  components/TaskList/TaskList.tsx
  components/kebab/KebabMenu.tsx
Labels: 🐞bug, 🏔️sprint_6

#218 feat: 성능 개선
  app/(workspace)/(note)/_components/noteCardList/NoteCardList.tsx
  app/(workspace)/goals/[id]/page.tsx
  app/(workspace)/todoList/page.tsx
  app/ModalArea.tsx
  components/TodoItem/TodoItem.tsx
  hooks/goalsDetail/useChangeGoalTitle.ts
  hooks/goalsDetail/useCheckTodoStatus.ts
  hooks/goalsDetail/useDeleteGoal.ts
  hooks/goalsDetail/useDeleteTodoItem.ts
  hooks/hooks.ts
  hooks/nav/useSetNewGoal.ts
  hooks/note/useDeleteNote.ts
  hooks/todo/useFilteredTodos.ts
  hooks/todo/useInfiniteTodoList.ts
  hooks/todoCreate/useSetTodoCreate.ts
  hooks/todoCreate/useTodoEdit.ts
  hooks/useDeleteTodoMutation.ts
  hooks/useUpdateTodoStatusMutation.ts
  modals/todoCreateModal/SubmitButton.tsx
  types/query.type.ts
Labels: 🏔️sprint_6

#226 fix: 노트 모아보기 페이지 url의 goalId가 잘못됐을 경우 오류 처리 수정
  apis/serverActions/goal.ts
Labels: 🏔️sprint_6

#228 refactor: next-pwa를 @serwist로 교체
  .gitignore
  app/layout.tsx
  app/sw.ts
  next.config.ts
  package.json
  tsconfig.json
Labels: ♻refactor

#204 feat: 비밀번호 암호화 추가
  apis/serverActions/goal.ts
  hooks/auth/useLoginMutation.ts
  hooks/auth/useSignUpMutation.ts
  package.json
  utils/cryptoUtils.ts
Labels: 🏔️sprint_6

#232 feat: 오프라인 페이지
  .github/workflows/main.yml
  app/sw.ts
  app/~offline/page.tsx
  next.config.ts
  tailwind.config.ts
  tsconfig.json
Labels: 🏔️sprint_6

#234 feat: 404 페이지 추가
  app/404/index.tsx
  app/not-found.tsx
  components/confettis/Confetti.tsx
  components/confettis/ConfettiFall.tsx
  tailwind.config.ts
Labels: 🏔️sprint_6
